# Generated by Django 4.1.1 on 2022-09-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_result", models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(name="Message",),
    ]
